# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ivtest_MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(929, 505)
        MainWindow.setMinimumSize(QtCore.QSize(929, 505))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.measurements = QtGui.QTabWidget(self.centralwidget)
        self.measurements.setObjectName(_fromUtf8("measurements"))
        self.iv = QtGui.QWidget()
        self.iv.setObjectName(_fromUtf8("iv"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.iv)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.iv)
        self.label.setMinimumSize(QtCore.QSize(112, 21))
        self.label.setMaximumSize(QtCore.QSize(112, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label, QtCore.Qt.AlignHCenter)
        self.VocSBox = QtGui.QSpinBox(self.iv)
        self.VocSBox.setMinimumSize(QtCore.QSize(119, 33))
        self.VocSBox.setMaximumSize(QtCore.QSize(119, 33))
        self.VocSBox.setMinimum(1)
        self.VocSBox.setMaximum(800)
        self.VocSBox.setProperty("value", 12)
        self.VocSBox.setObjectName(_fromUtf8("VocSBox"))
        self.verticalLayout.addWidget(self.VocSBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.iv)
        self.label_2.setMinimumSize(QtCore.QSize(116, 21))
        self.label_2.setMaximumSize(QtCore.QSize(116, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2, QtCore.Qt.AlignHCenter)
        self.limCurrSBox = QtGui.QSpinBox(self.iv)
        self.limCurrSBox.setMinimumSize(QtCore.QSize(119, 33))
        self.limCurrSBox.setMaximumSize(QtCore.QSize(119, 33))
        self.limCurrSBox.setProperty("value", 15)
        self.limCurrSBox.setObjectName(_fromUtf8("limCurrSBox"))
        self.verticalLayout_2.addWidget(self.limCurrSBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.iv)
        self.label_3.setMinimumSize(QtCore.QSize(116, 21))
        self.label_3.setMaximumSize(QtCore.QSize(116, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3, QtCore.Qt.AlignHCenter)
        self.stepSBox = QtGui.QDoubleSpinBox(self.iv)
        self.stepSBox.setMinimumSize(QtCore.QSize(129, 33))
        self.stepSBox.setMaximumSize(QtCore.QSize(129, 33))
        self.stepSBox.setDecimals(1)
        self.stepSBox.setMinimum(0.5)
        self.stepSBox.setMaximum(5.0)
        self.stepSBox.setSingleStep(0.5)
        self.stepSBox.setProperty("value", 1.0)
        self.stepSBox.setObjectName(_fromUtf8("stepSBox"))
        self.verticalLayout_3.addWidget(self.stepSBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.iv)
        self.label_4.setMinimumSize(QtCore.QSize(130, 21))
        self.label_4.setMaximumSize(QtCore.QSize(130, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.IrradcheckBox = QtGui.QCheckBox(self.iv)
        self.IrradcheckBox.setEnabled(False)
        self.IrradcheckBox.setToolTip(_fromUtf8(""))
        self.IrradcheckBox.setObjectName(_fromUtf8("IrradcheckBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.IrradcheckBox)
        self.label_5 = QtGui.QLabel(self.iv)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.IrrspinBox = QtGui.QSpinBox(self.iv)
        self.IrrspinBox.setMinimumSize(QtCore.QSize(129, 33))
        self.IrrspinBox.setMaximumSize(QtCore.QSize(129, 33))
        self.IrrspinBox.setMaximum(1500)
        self.IrrspinBox.setProperty("value", 1000)
        self.IrrspinBox.setObjectName(_fromUtf8("IrrspinBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.IrrspinBox)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.iv)
        self.label_6.setMinimumSize(QtCore.QSize(130, 21))
        self.label_6.setMaximumSize(QtCore.QSize(130, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.TempcheckBox = QtGui.QCheckBox(self.iv)
        self.TempcheckBox.setEnabled(False)
        self.TempcheckBox.setObjectName(_fromUtf8("TempcheckBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.TempcheckBox)
        self.label_7 = QtGui.QLabel(self.iv)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.TempspinBox = QtGui.QSpinBox(self.iv)
        self.TempspinBox.setMinimumSize(QtCore.QSize(129, 33))
        self.TempspinBox.setMaximumSize(QtCore.QSize(129, 33))
        self.TempspinBox.setMinimum(-20)
        self.TempspinBox.setMaximum(100)
        self.TempspinBox.setProperty("value", 25)
        self.TempspinBox.setObjectName(_fromUtf8("TempspinBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.TempspinBox)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.runButton = QtGui.QPushButton(self.iv)
        self.runButton.setObjectName(_fromUtf8("runButton"))
        self.horizontalLayout_3.addWidget(self.runButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.splitter = QtGui.QSplitter(self.iv)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.table = QtGui.QTableWidget(self.splitter)
        self.table.setMinimumSize(QtCore.QSize(441, 0))
        self.table.setMaximumSize(QtCore.QSize(500, 16777215))
        self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table.setAlternatingRowColors(True)
        self.table.setRowCount(10)
        self.table.setColumnCount(6)
        self.table.setObjectName(_fromUtf8("table"))
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        self.graphicsView = PlotWidget(self.splitter)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_6.addWidget(self.splitter)
        self.verticalLayout_20.addLayout(self.verticalLayout_6)
        self.measurements.addTab(self.iv, _fromUtf8(""))
        self.mpp = QtGui.QWidget()
        self.mpp.setObjectName(_fromUtf8("mpp"))
        self.layoutWidget = QtGui.QWidget(self.mpp)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 801, 251))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_16 = QtGui.QLabel(self.layoutWidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_13.addWidget(self.label_16)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_10 = QtGui.QLabel(self.layoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_7.addWidget(self.label_10, QtCore.Qt.AlignHCenter)
        self.pmax = QtGui.QSpinBox(self.layoutWidget)
        self.pmax.setMinimum(5)
        self.pmax.setMaximum(400)
        self.pmax.setObjectName(_fromUtf8("pmax"))
        self.verticalLayout_7.addWidget(self.pmax)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_8.addWidget(self.label_11, QtCore.Qt.AlignHCenter)
        self.Voc = QtGui.QSpinBox(self.layoutWidget)
        self.Voc.setObjectName(_fromUtf8("Voc"))
        self.verticalLayout_8.addWidget(self.Voc)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_9.addWidget(self.label_12, QtCore.Qt.AlignHCenter)
        self.Isc = QtGui.QSpinBox(self.layoutWidget)
        self.Isc.setObjectName(_fromUtf8("Isc"))
        self.verticalLayout_9.addWidget(self.Isc)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_10.addWidget(self.label_13, QtCore.Qt.AlignHCenter)
        self.Vpmax = QtGui.QSpinBox(self.layoutWidget)
        self.Vpmax.setObjectName(_fromUtf8("Vpmax"))
        self.verticalLayout_10.addWidget(self.Vpmax)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_14 = QtGui.QLabel(self.layoutWidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_11.addWidget(self.label_14, QtCore.Qt.AlignHCenter)
        self.Ipmax = QtGui.QSpinBox(self.layoutWidget)
        self.Ipmax.setObjectName(_fromUtf8("Ipmax"))
        self.verticalLayout_11.addWidget(self.Ipmax)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_15 = QtGui.QLabel(self.layoutWidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_12.addWidget(self.label_15, QtCore.Qt.AlignHCenter)
        self.dPmin = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.dPmin.setDecimals(2)
        self.dPmin.setMinimum(0.5)
        self.dPmin.setMaximum(2.0)
        self.dPmin.setSingleStep(0.01)
        self.dPmin.setObjectName(_fromUtf8("dPmin"))
        self.verticalLayout_12.addWidget(self.dPmin)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.runMPP = QtGui.QPushButton(self.layoutWidget)
        self.runMPP.setObjectName(_fromUtf8("runMPP"))
        self.horizontalLayout.addWidget(self.runMPP)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.verticalLayout_19.addLayout(self.verticalLayout_13)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem6)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_21 = QtGui.QLabel(self.layoutWidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_18.addWidget(self.label_21)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_17 = QtGui.QLabel(self.layoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(62, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_14.addWidget(self.label_17)
        self.lcdNumberMPP = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumberMPP.setMinimumSize(QtCore.QSize(101, 41))
        self.lcdNumberMPP.setObjectName(_fromUtf8("lcdNumberMPP"))
        self.verticalLayout_14.addWidget(self.lcdNumberMPP)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_18 = QtGui.QLabel(self.layoutWidget)
        self.label_18.setMinimumSize(QtCore.QSize(121, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_15.addWidget(self.label_18)
        self.lcdNumberVolt = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumberVolt.setMinimumSize(QtCore.QSize(101, 41))
        self.lcdNumberVolt.setObjectName(_fromUtf8("lcdNumberVolt"))
        self.verticalLayout_15.addWidget(self.lcdNumberVolt)
        self.horizontalLayout_2.addLayout(self.verticalLayout_15)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setMinimumSize(QtCore.QSize(121, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_16.addWidget(self.label_19)
        self.lcdNumberCurr = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumberCurr.setMinimumSize(QtCore.QSize(101, 41))
        self.lcdNumberCurr.setObjectName(_fromUtf8("lcdNumberCurr"))
        self.verticalLayout_16.addWidget(self.lcdNumberCurr)
        self.horizontalLayout_2.addLayout(self.verticalLayout_16)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_20 = QtGui.QLabel(self.layoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(121, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_17.addWidget(self.label_20)
        self.lcdNumberEnergy = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdNumberEnergy.setMinimumSize(QtCore.QSize(101, 41))
        self.lcdNumberEnergy.setObjectName(_fromUtf8("lcdNumberEnergy"))
        self.verticalLayout_17.addWidget(self.lcdNumberEnergy)
        self.horizontalLayout_2.addLayout(self.verticalLayout_17)
        self.verticalLayout_18.addLayout(self.horizontalLayout_2)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.measurements.addTab(self.mpp, _fromUtf8(""))
        self.gridLayout.addWidget(self.measurements, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 929, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDevice = QtGui.QMenu(self.menubar)
        self.menuDevice.setObjectName(_fromUtf8("menuDevice"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConnect_eload = QtGui.QAction(MainWindow)
        self.actionConnect_eload.setCheckable(True)
        self.actionConnect_eload.setObjectName(_fromUtf8("actionConnect_eload"))
        self.actionRead_eload = QtGui.QAction(MainWindow)
        self.actionRead_eload.setObjectName(_fromUtf8("actionRead_eload"))
        self.actionConnect_USB_2408 = QtGui.QAction(MainWindow)
        self.actionConnect_USB_2408.setCheckable(True)
        self.actionConnect_USB_2408.setObjectName(_fromUtf8("actionConnect_USB_2408"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionSetup_radiation_sensor = QtGui.QAction(MainWindow)
        self.actionSetup_radiation_sensor.setObjectName(_fromUtf8("actionSetup_radiation_sensor"))
        self.menuDevice.addAction(self.actionConnect_eload)
        self.menuDevice.addAction(self.actionRead_eload)
        self.menuDevice.addAction(self.actionSetup_radiation_sensor)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuDevice.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnect_eload)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnect_USB_2408)

        self.retranslateUi(MainWindow)
        self.measurements.setCurrentIndex(0)
        QtCore.QObject.connect(self.IrradcheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.IrrspinBox.setDisabled)
        QtCore.QObject.connect(self.TempcheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.TempspinBox.setDisabled)
        QtCore.QObject.connect(self.actionConnect_USB_2408, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.IrradcheckBox.setEnabled)
        QtCore.QObject.connect(self.actionConnect_USB_2408, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.TempcheckBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Voc Voltage (V)</span></p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Current limit (A)</span></p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Step voltage (V)</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Irradiation (W/m</span><span style=\" font-weight:600; vertical-align:super;\">2</span><span style=\" font-weight:600;\">)</span></p></body></html>", None))
        self.IrradcheckBox.setText(_translate("MainWindow", "Automatic", None))
        self.label_5.setText(_translate("MainWindow", "Manual", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Temperature (ºC)</span></p></body></html>", None))
        self.TempcheckBox.setText(_translate("MainWindow", "Automatic", None))
        self.label_7.setText(_translate("MainWindow", "Manual", None))
        self.runButton.setText(_translate("MainWindow", "Run", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Voltage (V)", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Current (A)", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Irrad (W/m2)", None))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CellTemp (ºC)", None))
        self.measurements.setTabText(self.measurements.indexOf(self.iv), _translate("MainWindow", "I-V", None))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Input values</span></p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "Pmax (W)", None))
        self.label_11.setText(_translate("MainWindow", "Voc (V)", None))
        self.label_12.setText(_translate("MainWindow", "Isc (A)", None))
        self.label_13.setText(_translate("MainWindow", "Vpmax (V)", None))
        self.label_14.setText(_translate("MainWindow", "Ipmax (A)", None))
        self.label_15.setText(_translate("MainWindow", "Delta Pmin", None))
        self.runMPP.setText(_translate("MainWindow", "Run MPP", None))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Measured values</span></p></body></html>", None))
        self.label_17.setText(_translate("MainWindow", "MPP (W)", None))
        self.label_18.setText(_translate("MainWindow", "Actual Voltage (V)", None))
        self.label_19.setText(_translate("MainWindow", "Actual Current (A)", None))
        self.label_20.setText(_translate("MainWindow", "Energy (Wh)", None))
        self.measurements.setTabText(self.measurements.indexOf(self.mpp), _translate("MainWindow", "MPP", None))
        self.menuDevice.setTitle(_translate("MainWindow", "Device", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionConnect_eload.setText(_translate("MainWindow", "Connect eload", None))
        self.actionRead_eload.setText(_translate("MainWindow", "Read eload ID", None))
        self.actionConnect_USB_2408.setText(_translate("MainWindow", "Connect USB-2408", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionSetup_radiation_sensor.setText(_translate("MainWindow", "Setup radiation sensor", None))

from pyqtgraph import PlotWidget
